config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :users, only: [:update, :show]

  authenticated :user do
    root to: 'total_camera#index', as: :pagina_logueo
  end
  root 'welcome#index'

  resources :events    

  get 'reports/index'
  get 'total_camera/index'

  resources :cameras do
    resources :events

    collection { post :import }

    collection do
      get 'conexion_humana'
      get 'propia'
      get 'arrendada'
      get 'colegio'
      get 'transmilenio'
      get 'ute'
      get 'index'
    end
    
  end

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :camera
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_camera

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    authorize @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    authorize @event
  end

  # GET /events/new
  def new
    @event = @camera.events.build
    authorize @event
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create   
    @event = @camera.events.create(event_params)
    authorize @event
    respond_to do |format|
      if @event.save
        format.html { redirect_to camera_path(@camera), notice: 'Novedad creada con éxito.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize @event
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to camera_path(@camera), notice: 'Novedad actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    authorize @event
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Novedad eliminada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_camera
      @camera = Camera.find(params[:camera_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:mebog, :fvs, :date, :camera_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<tr>
	<td><%= fecha event.date %></td>
	<td><%= event.mebog %></td>
	<td><%= event.fvs %></td>
	<td><%= link_to edit_camera_event_path(event.camera,event) do %>
      <i class="fa fa-pencil"></i>
    <% end %>
  </td>
</tr>

app/views/events/_form.html.erb
<%= form_for([@camera, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <div class="row">
      <div class="col-sm-2 col-md-2 col-lg-2"> 
        <%= f.label :date, "Fecha novedad" %><br>
        <%= f.text_field :date, class: "form-control datepicker" %>        
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-3 col-md-3 col-lg-3"> 
        <%= f.label :mebog, "Novedad MEBOG" %><br>
        <%= f.text_area :mebog, size: "15x6", class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-3 col-md-3 col-lg-3">
        <%= f.label :fvs, "Novedad FVS" %><br>
        <%= f.text_area :fvs, size: "15x6", class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-sm btn-info" %>

  <%= f.hidden_field :camera_id %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Back', camera_path(@camera), class: "btn btn-sm btn-primary" %>
</div>
<br>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Mebog</th>
      <th>Fvs</th>
      <th>Date</th>
      <th>Camera</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.mebog %></td>
        <td><%= event.fvs %></td>
        <td><%= event.date %></td>
        <td><%= event.camera %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', camera_path(@camera), class: "btn btn-sm btn-primary" %>
</div>
<br>

app/views/events/show.html.erb
<p>
  <strong>Mebog:</strong>
  <%= @event.mebog %>
</p>

<p>
  <strong>Fvs:</strong>
  <%= @event.fvs %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Camera:</strong>
  <%= @event.camera %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>