config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :users, only: [:update, :show]

  authenticated :user do
    root to: 'total_camera#index', as: :pagina_logueo
  end
  root 'welcome#index'

  resources :events    

  get 'reports/index'
  get 'total_camera/index'

  resources :cameras do
    resources :events

    collection { post :import }

    collection do
      get 'conexion_humana'
      get 'propia'
      get 'arrendada'
      get 'colegio'
      get 'transmilenio'
      get 'ute'
      get 'index'
    end
    
  end

  

end

app/models/camera.rb
class Camera < ActiveRecord::Base

	has_many :events

	paginates_per 15

  before_save :create_keywords

  scope :search, ->(keyword) { where('keywords LIKE ?', "%#{keyword.downcase}%") if keyword.present? }


	def self.import(file)
		CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
			camera_hash = row.to_hash		  
		  Camera.create!(camera_hash) unless Camera.exists?(spot: camera_hash[:spot], address: camera_hash[:address])
		end
	end	

	private
	def create_keywords
	    self.keywords = [spot, address, orientation, location, cosec].map(&:downcase).join(' ')
	end
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_action :set_camera, only: [:show, :edit, :update, :destroy]

  # GET /cameras
  # GET /cameras.json
  def index
    if params[:search].blank?
      @cameras = Camera.order(:location).all.page(params[:page]).per(params[:per])
      respond_to do |format|
        format.js { } 
        format.html
      end
      authorize @cameras
    else
      @cameras = Camera.search(params[:search]).page(params[:page]).per(params[:per])
      respond_to do |format|
        format.js 
        format.html
      end
      authorize @cameras
    end
  end

  # GET /cameras/1
  # GET /cameras/1.json
  def show
    authorize @camera
  end

  # GET /cameras/new
  def new    
    @camera = Camera.new
    authorize @camera
  end

  # GET /cameras/1/edit
  def edit
    authorize @camera
  end

  # POST /cameras
  # POST /cameras.json
  def create
    @camera = Camera.new(camera_params)
    authorize @camera
    respond_to do |format|
      if @camera.save
        format.html { redirect_to @camera, notice: 'Cámara creada con éxito.' }
        format.json { render :show, status: :created, location: @camera }
      else
        format.html { render :new }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cameras/1
  # PATCH/PUT /cameras/1.json
  def update    
    respond_to do |format|
      if @camera.update(camera_params)
        format.html { redirect_to @camera, notice: 'Cámara actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @camera }
        authorize @camera
      else
        format.html { render :edit }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cameras/1
  # DELETE /cameras/1.json
  def destroy    
    @camera.destroy
    respond_to do |format|
      format.html { redirect_to cameras_url, notice: 'Cámara eliminada con éxito.' }
      format.json { head :no_content }
    end
    authorize @camera
  end

  def import    
    respond_to do |format|  
      begin
        @cameras = Camera.import(params[:file])
        format.html { redirect_to cameras_url, notice: "Archivo subido con éxito" }
        format.json { render :index, status: :ok }
        authorize @cameras
      rescue
        format.html { redirect_to cameras_url, alert: "Archivo no subido, vuelve a intentarlo" }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end


  def conexion_humana    
    if params[:search].blank?
      @conexiones = Camera.where(project: 1).order(:location).all
      authorize @conexiones #page params[:page]      
    else
      @conexiones = Camera.where(project: 1).search
      authorize @conexiones
    end
  end

  def propia
    if params[:search].blank?
      @propias = Camera.where(project: 2).order(:location).all #page params[:page]
      authorize @propias
    else
      @propias = Camera.where(project: 2).search
      authorize @propias
    end
  end

  def arrendada
    if params[:search].blank?
      @arrendadas = Camera.where(project: 3).order(:location).all #page params[:page]
      authorize @arrendadas
    else
      @arrendadas = Camera.where(project: 3).search
      authorize @arrendadas
    end
  end

  def colegio
    if params[:search].blank?
      @colegios = Camera.where(project: 4).order(:location).all #page params[:page]
      authorize @colegios
    else
      @colegios = Camera.where(project: 4).search
      authorize @colegios
    end
  end

  def transmilenio
    if params[:search].blank?
      @transmilenios = Camera.where(project: 5).order(:location).all #page params[:page]
      authorize @transmilenios
    else
      @transmilenios = Camera.where(project: 5).search
      authorize @transmilenios
    end
  end

  def ute
    if params[:search].blank?
      @utes = Camera.where(project: 6).order(:location).all #page params[:page]
      authorize @utes
    else
      @utes = Camera.where(project: 6).search
      authorize @utes
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camera
      @camera = Camera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camera_params
      params.require(:camera).permit(:spot, :orientation, :address, :polygon, :condition, :cosec, :location, :lat, :lng, :project, :qty)
    end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/views/cameras/_camera.html.erb
<table class="table table-striped table-condensed"  id="cameras">
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Polígono</th>
      <th>Proyecto</th>
      <th>Punto</th>
      <th>Orientación</th>
      <th>Dirección</th>
      <th>Localidad</th>
      <th>Cosec</th>      
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody class="searchable">
    <% @cameras.each do |camera| %>
      <tr>
        <td><%= camera.qty %></td>
        <td><%= camera.polygon ? poligono : no_poligono %></td>
        <td><%= proyecto camera.project %></td>
        <td><%= camera.spot %></td>
        <td><%= camera.orientation %></td>
        <td><%= camera.address %></td>           
        <td><%= camera.location %></td>
        <td><%= camera.cosec %></td>
        <td><% if camera.condition? %>
              <div class="col-sm-1">
                  <div class="round round-sm green">
                      <%= bueno %>
                  </div>
              </div>
            <% else %>
              <div class="col-sm-1">
                  <div class="round round-sm red">
                      <%= malo %>
                  </div>
              </div>        
            <% end %>
        </td>           
        <td><%= link_to camera do %>
            <i class="fa fa-search"></i>
            <% end %>
        </td>            
        <td><%= link_to camera, method: :delete, data: { confirm: 'Está seguro?' }  do %>
            <span><i class="fa fa-trash btn-danger"></i></span>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>  
</table> 

app/views/cameras/arrendada.html.erb
<h1 class="text-center">Listado cámaras Arrendadas</h1>
<br>  
  <%= render "layouts/inicio" %>
<hr>
<%= render "layouts/buscar" %>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th>Cantidad</th>
          <th>Polígono</th>        
          <th>Punto</th>
          <th>Orientación</th>
          <th>Dirección</th>
          <th>Localidad</th>
          <th>Cosec</th>      
          <th>Estado</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @arrendadas.each do |camera| %>
          <tr>
            <td><%= camera.qty %></td>
            <td><%= camera.polygon ? poligono : no_poligono %></td>
            <td><%= camera.spot %></td>
            <td><%= camera.orientation %></td>
            <td><%= camera.address %></td>           
            <td><%= camera.location %></td>
            <td><%= camera.cosec %></td>
            <td><% if camera.condition? %>
                  <div class="col-sm-1">
                      <div class="round round-sm green">
                          <%= bueno %>
                      </div>
                  </div>
                <% else %>
                  <div class="col-sm-1">
                      <div class="round round-sm red">
                          <%= malo %>
                      </div>
                  </div>        
                <% end %>
            </td>
            <td><%= link_to camera do %>
                <i class="fa fa-search"></i>
                <% end %>
            </td>
            <td><%= link_to edit_camera_path(camera) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
            </td>
            <td><%= link_to camera, method: :delete, data: { confirm: 'Está seguro?' }  do %>
                <span><i class="fa fa-trash btn-danger"></i></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>
<br>
<div class="text-center">
  <%# paginate @arrendadas, :theme => 'twitter-bootstrap-3',
                         :pagination_class => "pagination-sm pagination-centered" %>
</div>

app/views/cameras/colegio.html.erb
<h1 class="text-center">Listado cámaras Colegios</h1>
<br>  
  <%= render "layouts/inicio" %>
<hr>
<%= render "layouts/buscar" %>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th>Cantidad</th>
          <th>Polígono</th>
          <th>Punto</th>
          <th>Orientación</th>
          <th>Dirección</th>
          <th>Localidad</th>
          <th>Cosec</th>      
          <th>Estado</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @colegios.each do |camera| %>
          <tr>
            <td><%= camera.qty %></td>
            <td><%= camera.polygon ? poligono : no_poligono %></td>
            <td><%= camera.spot %></td>
            <td><%= camera.orientation %></td>
            <td><%= camera.address %></td>           
            <td><%= camera.location %></td>
            <td><%= camera.cosec %></td>
            <td><% if camera.condition? %>
                  <div class="col-sm-1">
                      <div class="round round-sm green">
                          <%= bueno %>
                      </div>
                  </div>
                <% else %>
                  <div class="col-sm-1">
                      <div class="round round-sm red">
                          <%= malo %>
                      </div>
                  </div>        
                <% end %>
            </td>
            <td><%= link_to camera do %>
                <i class="fa fa-search"></i>
                <% end %>
            </td>
            <td><%= link_to edit_camera_path(camera) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
            </td>
            <td><%= link_to camera, method: :delete, data: { confirm: 'Está seguro?' }  do %>
                <span><i class="fa fa-trash btn-danger"></i></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>
<br>
<div class="text-center">
  <%# paginate @colegios, :theme => 'twitter-bootstrap-3',
                         :pagination_class => "pagination-sm pagination-centered" %>
</div>

app/views/cameras/conexion_humana.html.erb
<h1 class="text-center">Listado cámaras Conexión Humana <br>(Público - Privadas)</h1>
<br> 
  <%= render "layouts/inicio" %>
  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".bs-example-modal-lg">ver mapa</button>
<hr>
<%= render "layouts/buscar" %>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th>Cantidad</th>
          <th>Polígono</th>
          <th>Punto</th>
          <th>Orientación</th>
          <th>Dirección</th>
          <th>Localidad</th>
          <th>Cosec</th>      
          <th>Condición</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @conexiones.each do |camera| %>
          <tr>
            <td><%= camera.qty %></td>
            <td><%= camera.polygon ? poligono : no_poligono %></td>
            <td><%= camera.spot %></td>
            <td><%= camera.orientation %></td>
            <td><%= camera.address %></td>           
            <td><%= camera.location %></td>
            <td><%= camera.cosec %></td>
            <td><% if camera.condition? %>
                  <div class="col-sm-1">
                      <div class="round round-sm green">
                          <%= bueno %>
                      </div>
                  </div>
                <% else %>
                  <div class="col-sm-1">
                      <div class="round round-sm red">
                          <%= malo %>
                      </div>
                  </div>        
                <% end %>
            </td>           
            <td><%= link_to camera do %>
                <i class="fa fa-search"></i>
                <% end %>
            </td>
            <td><%= link_to edit_camera_path(camera) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
            </td>
            <td><%= link_to camera, method: :delete, data: { confirm: 'Está seguro?' }  do %>
                <span><i class="fa fa-trash btn-danger"></i></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>
<br>
<div class="text-center">
  <%# paginate @conexiones, :theme => 'twitter-bootstrap-3',
                         :pagination_class => "pagination-sm pagination-centered" %>
</div>


<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="mapa-completo" >
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <h4 class="text-center">Cámaras Conexión Humana</h4>
      <div id="content" class="pull-right" style="padding-right: 20px; margin-top: 20px;"></div>
      <div id="map-canvas"></div>      
    </div>
  </div>
</div>

<!--script map -->
<script>
  function initMap() {
  var map = new google.maps.Map(document.getElementById('map-canvas'), {
    zoom: 12,
    center: {lat: 37.06, lng: -95.68}
  });

  var kmlLayer = new google.maps.KmlLayer({
    url: 'https://www.dropbox.com/s/cm2hhgk46hsyjm5/doc.kml?dl=1',
    suppressInfoWindows: true,
    map: map
  });

  kmlLayer.addListener('click', function(kmlEvent) {
    var text = kmlEvent.featureData.description;
    showInContentWindow(text);
  });

  function showInContentWindow(text) {
    var sidediv = document.getElementById('content');
    sidediv.innerHTML = text;
  }

}
  $('#mapa-completo').on('shown.bs.modal', initMap);
  $(document).ready(initMap);
</script>

app/views/cameras/edit.html.erb
<h1>Editar Cámara</h1>

<%= render 'form' %>


<%= link_to  'Atrás', @camera, class: "btn btn-sm btn-primary" %>
</div>
<br>

app/views/cameras/index.html.erb
<h1 class="text-center">APLICATIVO DE VIDEO VIGILANCIA HUMANA</h1>
<p class="text-center">Listado completo de cámaras
  (Conexión Humana, Arrendadas, Propias, Colegios, Transmilenio y UTE)</p>

<div class="row text-center">
  <%= link_to conexion_humana_cameras_path do %>  
    <%= image_tag "logo_conexión_humana.jpg", size: "150x150" %>    
  <% end %>
  
  <%= link_to transmilenio_cameras_path do %>
    <%= image_tag "logo_sivit.jpg", size: "150x150" %>
  <% end %>    
</div>
  
  
<br>
<hr>
<div class="text-center">  
  <%= link_to '#listado', anchor: "listado" do %>
  <i class="fa fa-chevron-down"></i>
  <% end %>
</div>


<div class="row">
  <!--espacio de acomodo -->
  <br><br><br>
</div>
<div id="listado">
  <hr> 
  <%= form_tag(import_cameras_path, multipart: true, class: "archivo_plano") do %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-3 col-lg-3">
        <%= file_field_tag :file, required: true, class: "btn btn-sm btn-info" %>
        <p class="help-block"><strong>Nota: El archivo debe ser .csv</strong></p>
      </div>
      <div>
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>  
          <i class="fa fa-arrow-circle-up"></i>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>        

  <%= render "layouts/buscar" %>
  <div class="row">
    <div class="col-lg-12">
      <div class="table-responsive">      
          <%= render 'camera' %>
      </div>
    </div>
  </div>
  <div class="row text-center" id="paginator">
    <%= paginate @cameras, :remote => true,
                          :pagination_class => "pagination-sm pagination-centered" %>
  </div>
</div> 
<br>

app/views/cameras/index.js.erb
$('#cameras').html("<%= escape_javascript(render 'cameras/camera') %>");
$('#paginator').html("<%= escape_javascript(paginate(@cameras, :remote => true))  %>");

app/views/cameras/new.html.erb
<h1>Nueva Cámara</h1>

<%= render 'form' %>

<%= link_to 'Atrás', cameras_path, class: "btn btn-sm btn-primary" %>
</div>
<br>

app/views/cameras/propia.html.erb
<h1 class="text-center">Listado cámaras Propias</h1>
<br>  
  <%= render "layouts/inicio" %>
<hr>
<%= render "layouts/buscar" %>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th>Cantidad</th>
          <th>Polígono</th>
          <th>Punto</th>
          <th>Orientación</th>
          <th>Dirección</th>
          <th>Localidad</th>
          <th>Cosec</th>      
          <th>Estado</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @propias.each do |camera| %>
          <tr>
            <td><%= camera.qty %></td>
            <td><%= camera.polygon ? poligono : no_poligono %></td>
            <td><%= camera.spot %></td>
            <td><%= camera.orientation %></td>
            <td><%= camera.address %></td>           
            <td><%= camera.location %></td>
            <td><%= camera.cosec %></td>
            <td><% if camera.condition? %>
                  <div class="col-sm-1">
                      <div class="round round-sm green">
                          <%= bueno %>
                      </div>
                  </div>
                <% else %>
                  <div class="col-sm-1">
                      <div class="round round-sm red">
                          <%= malo %>
                      </div>
                  </div>        
                <% end %>
            </td>
            <td><%= link_to camera do %>
                <i class="fa fa-search"></i>
                <% end %>
            </td>
            <td><%= link_to edit_camera_path(camera) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
            </td>
            <td><%= link_to camera, method: :delete, data: { confirm: 'Está seguro?' }  do %>
                <span><i class="fa fa-trash btn-danger"></i></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>
<br>
<div class="text-center">
  <%# paginate @propias, :theme => 'twitter-bootstrap-3',
                         :pagination_class => "pagination-sm pagination-centered" %>
</div>

app/views/cameras/show.html.erb
<h3><p>Cámara perteneciente a: <strong><%= proyecto @camera.project %></strong></p></h3>
<br>
<%= link_to 'Atrás', ruta_atras(@camera.project), class: "btn btn-info btn-sm" %> 
<br><br>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Cantidad</th>
        <th>Polígono</th>
        <th>Punto</th>
        <th>Orientación</th>
        <th>Dirección</th>
        <th>Localidad</th>
        <th>Cosec</th>
        <th>Estado</th>
        <th colspan="2"></th>
      </tr>
        <tbody>
          <tr>
            <td><%= @camera.qty %></td>
            <td><%= @camera.polygon ? poligono : no_poligono %></td>
            <td><%= @camera.spot %></td>
            <td><%= @camera.orientation %></td>
            <td><%= @camera.address %></td>
            <td><%= @camera.location %></td>
            <td><%= @camera.cosec %></td>
            <td><% if @camera.condition? %>
                  <div class="col-sm-1">
                      <div class="round round-sm green">
                          <%= bueno %>
                      </div>
                  </div>
                <% else %>
                  <div class="col-sm-1">
                      <div class="round round-sm red">
                          <%= malo %>
                      </div>
                  </div>        
                <% end %>
            </td>
            <td class="text-center"><a href="#" data-toggle="modal" data-target="#mapa"><i class="fa fa-map-marker"></i></a></td>
            <td><%= link_to edit_camera_path(@camera) do %>
                  <i class="fa fa-pencil"></i>
                <% end %>
            </td>
          </tr>
        </tbody>      
    </thead>
  </table>
</div>

<br>

<div class="panel panel-info">
  <div class="panel-heading">
    <br>
    <h3 class="panel-title">
      <%= link_to new_camera_event_path(@camera), class: "pull-right" do %>
        <i class="fa fa-plus"></i> 
      <% end %>
    <a href="#" data-toggle="collapse" data-target="#Acordeon" aria-expanded="false" aria-controls="Acordeon"><strong>Novedades</strong></a>
    </h3> 
    <br>      
  </div>
  <div class="panel-body">
    <div class="collapse" id="Acordeon">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Novedad Mebog</th>
              <th>Novedad FVS</th>              
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= render @camera.events %>            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<!-- Mapa -->
<% if @camera.lat.present? %>  
  <center>
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="mapa" >
      <div class="modal-dialog modal-lg">
        <div class="modal-content">          
          <div id="map-canvas" ></div>
        </div>

      </div>
    </div>

    <div class="mapa">
      <div id="map-canvas"></div>
    </div>    
  </center>
<% end %>
<br>

<%= link_to 'Atrás', ruta_atras(@camera.project), class: "btn btn-info btn-sm" %> <%= link_to root_path, class: "btn btn-primary btn-sm pull-right"  do%>
  <i class="fa fa-home"></i>
<% end %>

<br><br>

<!--script map -->
<script>
  function initialize() {

    var myLatlng = new google.maps.LatLng(<%= @camera.lat %>, <%= @camera.lng %>);
    var mapOptions = {
      zoom: 15,
      center: myLatlng
    }
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var marker = new google.maps.Marker({
        position: myLatlng,
        map: map,
        title: 'Cámara'
    });
  }
  
  $('#mapa').on('shown.bs.modal', initialize);
  $(document).ready(initialize);
</script>

app/views/cameras/transmilenio.html.erb
<h1 class="text-center">Listado cámaras Transmilenio</h1>
<br>  
  <%= render "layouts/inicio" %>
<hr>
<%= render "layouts/buscar" %>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th>Cantidad</th>
          <th>Polígono</th>
          <th>Punto</th>
          <th>Orientación</th>
          <th>Dirección</th>
          <th>Localidad</th>
          <th>Cosec</th>      
          <th>Estado</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @transmilenios.each do |camera| %>
          <tr>
            <td><%= camera.qty %></td>
            <td><%= camera.polygon ? poligono : no_poligono %></td>
            <td><%= camera.spot %></td>
            <td><%= camera.orientation %></td>
            <td><%= camera.address %></td>           
            <td><%= camera.location %></td>
            <td><%= camera.cosec %></td>
            <td><% if camera.condition? %>
                  <div class="col-sm-1">
                      <div class="round round-sm green">
                          <%= bueno %>
                      </div>
                  </div>
                <% else %>
                  <div class="col-sm-1">
                      <div class="round round-sm red">
                          <%= malo %>
                      </div>
                  </div>        
                <% end %>
            </td>
            <td><%= link_to camera do %>
                <i class="fa fa-search"></i>
                <% end %>
            </td>
            <td><%= link_to edit_camera_path(camera) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
            </td>
            <td><%= link_to camera, method: :delete, data: { confirm: 'Está seguro?' }  do %>
                <span><i class="fa fa-trash btn-danger"></i></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>
<br>
<div class="text-center">
  <%# paginate @transmilenios, :theme => 'twitter-bootstrap-3',
                         :pagination_class => "pagination-sm pagination-centered" %>
</div>

app/views/cameras/ute.html.erb
<h1 class="text-center">Listado cámaras UTE</h1>
<br>   
  <%= render "layouts/inicio" %>
<hr>
<%= render "layouts/buscar" %>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th>Cantidad</th>
          <th>Polígono</th>
          <th>Punto</th>
          <th>Orientación</th>
          <th>Dirección</th>
          <th>Localidad</th>
          <th>Cosec</th>      
          <th>Estado</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @utes.each do |camera| %>
          <tr>
            <td><%= camera.qty %></td>
            <td><%= camera.polygon ? poligono : no_poligono %></td>
            <td><%= camera.spot %></td>
            <td><%= camera.orientation %></td>
            <td><%= camera.address %></td>           
            <td><%= camera.location %></td>
            <td><%= camera.cosec %></td>
            <td><% if camera.condition? %>
                  <div class="col-sm-1">
                      <div class="round round-sm green">
                          <%= bueno %>
                      </div>
                  </div>
                <% else %>
                  <div class="col-sm-1">
                      <div class="round round-sm red">
                          <%= malo %>
                      </div>
                  </div>        
                <% end %>
            </td>
            <td><%= link_to camera do %>
                <i class="fa fa-search"></i>
                <% end %>
            </td>
            <td><%= link_to edit_camera_path(camera) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
            </td>
            <td><%= link_to camera, method: :delete, data: { confirm: 'Está seguro?' }  do %>
                <span><i class="fa fa-trash btn-danger"></i></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>
<br>
<div class="text-center">
  <%# paginate @utes, :theme => 'twitter-bootstrap-3',
                         :pagination_class => "pagination-sm pagination-centered" %>
</div>