config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :users, only: [:update, :show]

  authenticated :user do
    root to: 'total_camera#index', as: :pagina_logueo
  end
  root 'welcome#index'

  resources :events    

  get 'reports/index'
  get 'total_camera/index'

  resources :cameras do
    resources :events

    collection { post :import }

    collection do
      get 'conexion_humana'
      get 'propia'
      get 'arrendada'
      get 'colegio'
      get 'transmilenio'
      get 'ute'
      get 'index'
    end
    
  end

  

end

app/views/layouts/_alert.html.erb
<div class="alert 
    <%= 
    case type.to_sym 
    when :alert, :danger, :error, :validation_errors
        'notice notice-danger'
    when :warning, :todo
        'notice notice-warning'
    when :notice, :success
        'notice notice-success'
    else 
        'notice notice-info'
    end
    %>
     alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
    <%= content %>
</div>

app/views/layouts/_buscar.html.erb
<!-- <div class="row pull-right"> -->
  <div class="col-lg-4 col-lg-offset-4">
    <div class="input-group">
      <%= form_tag cameras_path, method: 'get' do %>
        <%= text_field_tag :search, nil, class: "form-control", placeholder: "Buscar cámaras..." %>
      <% end %>
      <span class="input-group-btn">      
        <%= link_to '#', class: "btn btn-info" do  %> 
        <i class="fa fa-search"></i>
        <% end %>
      </span>      
    </div> 
  </div>
  <br>
<!-- </div> -->

app/views/layouts/_inicio.html.erb
<%= link_to 'Atrás', cameras_path, class: "btn btn-info btn-sm" %>

<%= link_to new_camera_path, class: "btn btn-info btn-sm pull-right" do %>
  <i class="fa fa-plus"></i> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FVS</title>

  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :additional_assets %>
</head>
<body> 
  <nav class="navbar navbar-white navbar-fixed-top" role="navigation">    
    <div class="container">      
      <br>        
       
      <ul class="nav navbar-nav navbar-right" style="margin-top: -10px;">
        
        <%= link_to root_path, class: "nav-brand pull-left", style: "margin-top: 10px; padding-right: 5px;" do  %>
            <i class="fa fa-home fa-2x"></i>
          <% end %>         
        <% if current_user %> 
          <li><%# link_to "Perfil", current_user %></li>
          <p class="navbar-text">
            Hola,  
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name || current_user.email %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to edit_user_registration_path do %>
                     <i class="fa fa-pencil"> Editar</i>
                    <% end %>
                </li>
                <li role="separator" class="divider"></li>
                <li><%= link_to destroy_user_session_path, method: :delete, data: {confirm: "Estás Seguro de Salir?"} do %>
                     <i class="fa fa-sign-out"> Salir</i>                
                    <% end %>
                </li>
              </ul>
            </li>            
          </p>
        <% else %> 
        <ul class="nav navbar-nav"> 
          <li><%# link_to "Regístrate", new_user_registration_path %></li>
          <li><%= link_to "Ingresa", new_user_session_path, id: "login", class: "nav-brand pull-right" %></li>
        </ul>
      <% end %>
      </ul>
      <% flash.each do |type, content| %>
        <% if content.respond_to?('each') 
          content.each do |item| %>
            <%= render 'layouts/alert', type: type, content: item %>
          <% end %>
          <% else %>
            <%= render 'layouts/alert', type: type, content: content %>
        <% end %>
      <% end %>
    </div>      
  </nav>    
  <br>
	<div class="container-fluid">
    <br><br>
		<%= yield %>
    <%= yield :reports %>
	</div>
</body>
</html>